version: '3'
services:
  poll:
    container_name: poll
    build: ./poll
    ports:
      - 5000:80
    networks:
      - poll-tier
    links: 
      - redis
      - db
    environment: 
      - 0.0.0.0
    restart: always
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - poll-tier
      - back-tier
    restart: always
  worker:
    container_name: worker
    build: ./worker
    networks:
      - back-tier
    environment: 
      - 0.0.0.0
    restart: always
  db:
    image: postgres:9.4
    container_name: db
    networks:
      - result-tier
      - back-tier
    volumes:
      - db-data:/var/lib/postgresql/data
    environment: 
      - 0.0.0.0
    restart: always
  result:
    build: ./result
    ports:
      - 5001:80
    networks:
      - result-tier
    environment: 
      - 0.0.0.0
    restart: always

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data:
